USE IITP_Timetable;

-- 1. Add the new 'Lab' column to the course table
ALTER TABLE course ADD COLUMN Lab VARCHAR(20) DEFAULT NULL;

-- 2. Update courses where P > 0
BEGIN;

UPDATE course SET Lab = 'CBLAB1' WHERE Course_ID = 'CB2201';
UPDATE course SET Lab = 'CBLAB1' WHERE Course_ID = 'CB2204';
UPDATE course SET Lab = 'CBLAB1' WHERE Course_ID = 'CB3204';
UPDATE course SET Lab = 'CBWORKSHOP' WHERE Course_ID = 'CB5203';
UPDATE course SET Lab = 'CEWORKSHOP' WHERE Course_ID = 'CE1201';
UPDATE course SET Lab = 'CELAB1' WHERE Course_ID = 'CE2201';
UPDATE course SET Lab = 'CELAB1' WHERE Course_ID = 'CE2202';
UPDATE course SET Lab = 'CELAB2' WHERE Course_ID = 'CE2203';
UPDATE course SET Lab = 'CEWORKSHOP' WHERE Course_ID = 'CE3205';
UPDATE course SET Lab = 'CEWORKSHOP' WHERE Course_ID = 'CE5202';
UPDATE course SET Lab = 'CELAB2' WHERE Course_ID = 'CE5205';
UPDATE course SET Lab = 'CELAB2' WHERE Course_ID = 'CE5207';
UPDATE course SET Lab = 'CEWORKSHOP' WHERE Course_ID = 'CE5209';
UPDATE course SET Lab = 'CELAB2' WHERE Course_ID = 'CE5210';
UPDATE course SET Lab = 'CELAB2' WHERE Course_ID = 'CE5212';
UPDATE course SET Lab = 'CHLAB1' WHERE Course_ID = 'CH1201';
UPDATE course SET Lab = 'CHLAB1' WHERE Course_ID = 'CH2205';
UPDATE course SET Lab = 'CHLAB1' WHERE Course_ID = 'CH3203';
UPDATE course SET Lab = 'CHLAB2' WHERE Course_ID = 'CH3205';
UPDATE course SET Lab = 'CHLAB2' WHERE Course_ID = 'CH4206';
UPDATE course SET Lab = 'CHLAB1' WHERE Course_ID = 'CH6201';
UPDATE course SET Lab = 'CSLAB' WHERE Course_ID = 'CS1201';
UPDATE course SET Lab = 'HDWLAB' WHERE Course_ID = 'CS2202';
UPDATE course SET Lab = 'CSLAB' WHERE Course_ID = 'CS2203';
UPDATE course SET Lab = 'CC1' WHERE Course_ID = 'CS2204';
UPDATE course SET Lab = 'CC1' WHERE Course_ID = 'CS2205';
UPDATE course SET Lab = 'HDWLAB' WHERE Course_ID = 'CS2206';
UPDATE course SET Lab = 'CSLAB' WHERE Course_ID = 'CS3201';
UPDATE course SET Lab = 'HDWLAB' WHERE Course_ID = 'CS3202';
UPDATE course SET Lab = 'CSLAB' WHERE Course_ID = 'CS3203';
UPDATE course SET Lab = 'CSLAB' WHERE Course_ID = 'CS3204';
UPDATE course SET Lab = 'CC1' WHERE Course_ID = 'CS5204';
UPDATE course SET Lab = 'CC1' WHERE Course_ID = 'CS5205';
UPDATE course SET Lab = 'EELAB1' WHERE Course_ID = 'EC2201';
UPDATE course SET Lab = 'EEWORKSHOP' WHERE Course_ID = 'EC2202';
UPDATE course SET Lab = 'EELAB2' WHERE Course_ID = 'EC3201';
UPDATE course SET Lab = 'EEWORKSHOP' WHERE Course_ID = 'EC3202';
UPDATE course SET Lab = 'EELAB1' WHERE Course_ID = 'EC5201';
UPDATE course SET Lab = 'EELAB1' WHERE Course_ID = 'EC5202';
UPDATE course SET Lab = 'EEWORKSHOP' WHERE Course_ID = 'EC5203';
UPDATE course SET Lab = 'EELAB2' WHERE Course_ID = 'EC5204';
UPDATE course SET Lab = 'EELAB1' WHERE Course_ID = 'EE1201';
UPDATE course SET Lab = 'EELAB1' WHERE Course_ID = 'EE2201';
UPDATE course SET Lab = 'EEWORKSHOP' WHERE Course_ID = 'EE2202';
UPDATE course SET Lab = 'EEWORKSHOP' WHERE Course_ID = 'EE3201';
UPDATE course SET Lab = 'EEWORKSHOP' WHERE Course_ID = 'EE3202';
UPDATE course SET Lab = 'EELAB2' WHERE Course_ID = 'EE3203';
UPDATE course SET Lab = 'EELAB2' WHERE Course_ID = 'EE3204';
UPDATE course SET Lab = 'EELAB2' WHERE Course_ID = 'EE5201';
UPDATE course SET Lab = 'EELAB2' WHERE Course_ID = 'EE5202';
UPDATE course SET Lab = 'PHLAB2' WHERE Course_ID = 'EP2205';
UPDATE course SET Lab = 'PHLAB2' WHERE Course_ID = 'EP3202';
UPDATE course SET Lab = 'PHLAB2' WHERE Course_ID = 'EP3203';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA2201';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA2203';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA2204';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA2205';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA3202';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA3204';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA3206';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA4202';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MA4204';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MC5202';
UPDATE course SET Lab = 'MALAB1' WHERE Course_ID = 'MC5203';
UPDATE course SET Lab = 'MELAB2' WHERE Course_ID = 'ME1201';
UPDATE course SET Lab = 'MELAB1' WHERE Course_ID = 'ME2201';
UPDATE course SET Lab = 'MELAB1' WHERE Course_ID = 'ME2202';
UPDATE course SET Lab = 'MELAB2' WHERE Course_ID = 'ME2204';
UPDATE course SET Lab = 'MELAB2' WHERE Course_ID = 'ME3201';
UPDATE course SET Lab = 'MELAB2' WHERE Course_ID = 'ME3202';
UPDATE course SET Lab = 'MELAB2' WHERE Course_ID = 'ME3203';
UPDATE course SET Lab = 'MELAB1' WHERE Course_ID = 'ME3205';
UPDATE course SET Lab = 'MELAB2' WHERE Course_ID = 'ME5201';
UPDATE course SET Lab = 'MELAB1' WHERE Course_ID = 'ME5204';
UPDATE course SET Lab = 'MELAB1' WHERE Course_ID = 'ME5206';
UPDATE course SET Lab = 'MEWORKSHOP' WHERE Course_ID = 'ME5208';
UPDATE course SET Lab = 'MMELAB1' WHERE Course_ID = 'MM2202';
UPDATE course SET Lab = 'MMWORKSHOP' WHERE Course_ID = 'MM2204';
UPDATE course SET Lab = 'MMELAB1' WHERE Course_ID = 'MM3201';
UPDATE course SET Lab = 'MMWORKSHOP' WHERE Course_ID = 'MM3202';
UPDATE course SET Lab = 'MMELAB1' WHERE Course_ID = 'MM3205';
UPDATE course SET Lab = 'MMWORKSHOP' WHERE Course_ID = 'MM3206';
UPDATE course SET Lab = 'MMELAB1' WHERE Course_ID = 'MM5201';
UPDATE course SET Lab = 'MMELAB1' WHERE Course_ID = 'MM5202';
UPDATE course SET Lab = 'PHLAB1' WHERE Course_ID = 'PH1201';
UPDATE course SET Lab = 'PHLAB1' WHERE Course_ID = 'PH4203';
UPDATE course SET Lab = 'PHLAB1' WHERE Course_ID = 'PH5201';

COMMIT;
